export const subex_wf = [
  "/images/subex/wf/01.png",
  "/images/subex/wf/01_Case_Configuration.png",
  "/images/subex/wf/02.png",
  "/images/subex/wf/02_Work_Step.png",
  "/images/subex/wf/03.png",
  "/images/subex/wf/03_Case_Investigation.png",
  "/images/subex/wf/03_Case_Listing_page.png",
  "/images/subex/wf/07_Forward_Case.png",
  "/images/subex/wf/08_Close_Case.png",
  "/images/subex/wf/09_Bulk_Close_Case.png",
  "/images/subex/wf/10_Closed_Case.png",
  "/images/subex/wf/11_Reopen_Case.png",
  "/images/subex/wf/12_Comment_to_Reopen.png",
  "/images/subex/wf/13_Case_Reopned.png",
  "/images/subex/wf/14_Case_Reporting.png",
];

export const subex_vd = [
  "/images/subex/vd/01.png",
  "/images/subex/vd/03.png",
  "/images/subex/vd/05.png",
  "/images/subex/vd/06.png",
  "/images/subex/vd/07.png",
  "/images/subex/vd/09.png",
];

export const sbsa_wf = [
  "/images/sbsa/wf/Selecting_1_account.png",
  "/images/sbsa/wf/Selecting_All_Accounts.png",
  "/images/sbsa/wf/Selecting_Multiple_Accounts.png",
  "/images/sbsa/wf/Selecting_multiple_subgroups_account_groups.png",
  "/images/sbsa/wf/View_sub_group_details.png",
  "/images/sbsa/wf/View_subgroups.png",
];

export const sbsa_vd = [
  "/images/sbsa/vd/Account_Balances_Multi_Select.png",
  "/images/sbsa/vd/Accounts Sub Group_Advance_Search.png",
  "/images/sbsa/vd/Accounts_Sub Group_Consolidation Popup_Single_Account_SG_Selected_Expanded.png",
  "/images/sbsa/vd/Advance_Search_No_Account_Selected.png",
  "/images/sbsa/vd/Basic_Search_Accounts_Sub_Group_1_ASG.png",
  "/images/sbsa/vd/Consolidation Popup_Selcting_Accounts.png",
  "/images/sbsa/vd/Consolidation_On_Existing_Screen.png",
  "/images/sbsa/vd/Consolidation_Popup_1_AccountSB Selected_Collpased.png",
  "/images/sbsa/vd/Consolidation_Popup_1_AccountSB_Selected_Select_different_Account_SGs.png",
  "/images/sbsa/vd/Consolidation_Popup_Multiple Account_Selected_Select_diffferent_account.png",
  "/images/sbsa/vd/Consolidation_Popup_Multiple _Account_Selected_Collapsed.png",
  "/images/sbsa/vd/Consolidation_Popup_no_Account_Selected_Collapsed.png",
  "/images/sbsa/vd/Consolidation_Popup_no_Account_Selected_Select_diffferent_account.png",
  "/images/sbsa/vd/Consolidation_Result.png",
  "/images/sbsa/vd/Consolidation_popup_Single_Account_Selected_Collapsed.png",
  "/images/sbsa/vd/Edit_consolidation_criteria.png",
  "/images/sbsa/vd/Edit_consolidation_criteria_Copy.png",
  "/images/sbsa/vd/account_balances_Single Account_Selected_Select_diffferent_account.png",
];

export const mtbp_wf = [
  "/images/mtbp/wf/1.png",
  "/images/mtbp/wf/10.png",
  "/images/mtbp/wf/11.png",
  "/images/mtbp/wf/12.png",
  "/images/mtbp/wf/13.png",
  "/images/mtbp/wf/14.png",
  "/images/mtbp/wf/2.png",
  "/images/mtbp/wf/3.png",
  "/images/mtbp/wf/4.png",
  "/images/mtbp/wf/5.png",
  "/images/mtbp/wf/6.png",
  "/images/mtbp/wf/7.png",
  "/images/mtbp/wf/8.png",
  "/images/mtbp/wf/9.png",
];

export const mtbp_vd = [
  "/images/mtbp/vd/01_Login.png",
  "/images/mtbp/vd/02_Dashboard.png",
  "/images/mtbp/vd/03_Customer_Data.png",
  "/images/mtbp/vd/04_Customer_Data.png",
  "/images/mtbp/vd/05_KYC_Check.png",
  "/images/mtbp/vd/06_KYC_Check.png",
  "/images/mtbp/vd/07_TelePD.png",
  "/images/mtbp/vd/08_TU_Re-hit.png",
  "/images/mtbp/vd/09_CIBIL_Check.png",
  "/images/mtbp/vd/10_Fill_Data.png",
  "/images/mtbp/vd/11_Curing.png",
];

export const dell_wf = [
  "/images/dell/wf/01_AdvanceSearch–2.png",
  "/images/dell/wf/01_AdvanceSearch–3.png",
  "/images/dell/wf/01_AdvanceSearch–4.png",
  "/images/dell/wf/01_AdvanceSearch–5.png",
  "/images/dell/wf/01_AdvanceSearch–6.png",
  "/images/dell/wf/01_ReturningUserDefault–1.png",
  "/images/dell/wf/01_ReturningUserDefault–2.png",
  "/images/dell/wf/01_ReturningUserDefault–3.png",
  "/images/dell/wf/01_ReturningUserDefault–4.png",
  "/images/dell/wf/01_ReturningUserDefault–5.png",
  "/images/dell/wf/01_ReturningUserDefault–6.png",
  "/images/dell/wf/01_ReturningUserDefault–7.png",
  "/images/dell/wf/06_New Concept_Help.png",
];

export const dell_vd = [
  "/images/dell/vd/Dell-FAP_01.png",
  "/images/dell/vd/Dell-FAP_02.png",
  "/images/dell/vd/Dell-FAP_03.png",
  "/images/dell/vd/Dell-FAP_04.png",
  "/images/dell/vd/Dell-FAP_05.png",
  "/images/dell/vd/Dell-FAP_06.png",
  "/images/dell/vd/Dell-FAP_07.png",
  "/images/dell/vd/Dell-FAP_08.png",
  "/images/dell/vd/Dell-FAP_09.png",
  "/images/dell/vd/Dell-FAP_10.png",
  "/images/dell/vd/Dell-FAP_11.png",
  "/images/dell/vd/Dell-FAP_12.png",
  "/images/dell/vd/Mob1.png",
  "/images/dell/vd/Mob2.png",
  "/images/dell/vd/Mob3.png",
];

export const trippiez_wf = [
  "/images/trippiez/wf/01_Trippiez.png",
  "/images/trippiez/wf/02_Trippiez.png",
  "/images/trippiez/wf/03_Trippiez.png",
  "/images/trippiez/wf/04_Trippiez.png",
  "/images/trippiez/wf/05_Trippiez.png",
  "/images/trippiez/wf/06_Trippiez.png",
  "/images/trippiez/wf/07_Trippiez.png",
  "/images/trippiez/wf/08_Trippiez.png",
  "/images/trippiez/wf/09_Trippiez.png",
  "/images/trippiez/wf/10_Trippiez.png",
  "/images/trippiez/wf/11_Trippiez.png",
  "/images/trippiez/wf/12_Trippiez.png",
  "/images/trippiez/wf/13_Trippiez.png",
];
